#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNS2013")]
public partial class QLNS2013DBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertDMNganSach(DMNganSach instance);
  partial void UpdateDMNganSach(DMNganSach instance);
  partial void DeleteDMNganSach(DMNganSach instance);
  partial void InsertDmChiPhi(DmChiPhi instance);
  partial void UpdateDmChiPhi(DmChiPhi instance);
  partial void DeleteDmChiPhi(DmChiPhi instance);
  partial void InsertDmNhomNganSach(DmNhomNganSach instance);
  partial void UpdateDmNhomNganSach(DmNhomNganSach instance);
  partial void DeleteDmNhomNganSach(DmNhomNganSach instance);
  partial void InsertTaiKhoanNganHang(TaiKhoanNganHang instance);
  partial void UpdateTaiKhoanNganHang(TaiKhoanNganHang instance);
  partial void DeleteTaiKhoanNganHang(TaiKhoanNganHang instance);
  partial void InsertImportTaiKhoanNganHang_tmp(ImportTaiKhoanNganHang_tmp instance);
  partial void UpdateImportTaiKhoanNganHang_tmp(ImportTaiKhoanNganHang_tmp instance);
  partial void DeleteImportTaiKhoanNganHang_tmp(ImportTaiKhoanNganHang_tmp instance);
  #endregion
	
	public QLNS2013DBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectDB_QLNS2013"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public QLNS2013DBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QLNS2013DBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QLNS2013DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QLNS2013DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<DMNganSach> DMNganSaches
	{
		get
		{
			return this.GetTable<DMNganSach>();
		}
	}
	
	public System.Data.Linq.Table<DmChiPhi> DmChiPhis
	{
		get
		{
			return this.GetTable<DmChiPhi>();
		}
	}
	
	public System.Data.Linq.Table<DmNhomNganSach> DmNhomNganSaches
	{
		get
		{
			return this.GetTable<DmNhomNganSach>();
		}
	}
	
	public System.Data.Linq.Table<TaiKhoanNganHang> TaiKhoanNganHangs
	{
		get
		{
			return this.GetTable<TaiKhoanNganHang>();
		}
	}
	
	public System.Data.Linq.Table<ImportTaiKhoanNganHang_tmp> ImportTaiKhoanNganHang_tmps
	{
		get
		{
			return this.GetTable<ImportTaiKhoanNganHang_tmp>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ChiPhi_DELETE_LOG")]
	public int sp_ChiPhi_DELETE_LOG([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCP", DbType="VarChar(50)")] string maCP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNganSach", DbType="VarChar(50)")] string maNganSach, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="VarChar(50)")] string mANV)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCP, maNganSach, mANV);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ChuyenNganSachThuaCuaThangTruoc")]
	public ISingleResult<sp_ChuyenNganSachThuaCuaThangTruocResult> sp_ChuyenNganSachThuaCuaThangTruoc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Khoa", DbType="VarChar(50)")] string iD_Khoa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSChiPhi", DbType="VarChar(50)")] string mSChiPhi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNV", DbType="VarChar(50)")] string maNV)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Khoa, mSChiPhi, maNV);
		return ((ISingleResult<sp_ChuyenNganSachThuaCuaThangTruocResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_KiemTraNganSachDu")]
	public ISingleResult<Sp_KiemTraNganSachDuResult> Sp_KiemTraNganSachDu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Khoa", DbType="VarChar(50)")] string iD_Khoa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MACP", DbType="VarChar(50)")] string mACP)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Khoa, mACP);
		return ((ISingleResult<Sp_KiemTraNganSachDuResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_UpdateNganSachSauKhiChuyenThua")]
	public ISingleResult<Sp_UpdateNganSachSauKhiChuyenThuaResult> Sp_UpdateNganSachSauKhiChuyenThua([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Khoa", DbType="VarChar(50)")] string iD_Khoa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MACP", DbType="VarChar(50)")] string mACP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thang", DbType="Int")] System.Nullable<int> thang)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Khoa, mACP, thang);
		return ((ISingleResult<Sp_UpdateNganSachSauKhiChuyenThuaResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsert_TaiKhoanNganHang")]
	public int spInsert_TaiKhoanNganHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MADV", DbType="VarChar(50)")] string mADV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="VarChar(50)")] string mANV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenNganHang", DbType="VarChar(50)")] string tenNganHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoTaiKhoan", DbType="VarChar(50)")] string soTaiKhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ghichu", DbType="NVarChar(MAX)")] string ghichu)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mADV, mANV, tenNganHang, soTaiKhoan, ghichu);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDelete_TaiKhoanNganHang")]
	public int spDelete_TaiKhoanNganHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spUpdate_TaiKhoanNganHang")]
	public int spUpdate_TaiKhoanNganHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MADV", DbType="VarChar(50)")] string mADV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="VarChar(50)")] string mANV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenNganHang", DbType="VarChar(50)")] string tenNganHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoTaiKhoan", DbType="VarChar(50)")] string soTaiKhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ghichu", DbType="NVarChar(MAX)")] string ghichu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mADV, mANV, tenNganHang, soTaiKhoan, ghichu, iD);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DMNganSach")]
public partial class DMNganSach : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaNganSach;
	
	private string _DienGiai;
	
	private string _MaNhomNS;
	
	private System.Nullable<bool> _HieuLuc_NS;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNganSachChanging(string value);
    partial void OnMaNganSachChanged();
    partial void OnDienGiaiChanging(string value);
    partial void OnDienGiaiChanged();
    partial void OnMaNhomNSChanging(string value);
    partial void OnMaNhomNSChanged();
    partial void OnHieuLuc_NSChanging(System.Nullable<bool> value);
    partial void OnHieuLuc_NSChanged();
    #endregion
	
	public DMNganSach()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNganSach", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaNganSach
	{
		get
		{
			return this._MaNganSach;
		}
		set
		{
			if ((this._MaNganSach != value))
			{
				this.OnMaNganSachChanging(value);
				this.SendPropertyChanging();
				this._MaNganSach = value;
				this.SendPropertyChanged("MaNganSach");
				this.OnMaNganSachChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienGiai", DbType="NVarChar(200)")]
	public string DienGiai
	{
		get
		{
			return this._DienGiai;
		}
		set
		{
			if ((this._DienGiai != value))
			{
				this.OnDienGiaiChanging(value);
				this.SendPropertyChanging();
				this._DienGiai = value;
				this.SendPropertyChanged("DienGiai");
				this.OnDienGiaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomNS", DbType="VarChar(10)")]
	public string MaNhomNS
	{
		get
		{
			return this._MaNhomNS;
		}
		set
		{
			if ((this._MaNhomNS != value))
			{
				this.OnMaNhomNSChanging(value);
				this.SendPropertyChanging();
				this._MaNhomNS = value;
				this.SendPropertyChanged("MaNhomNS");
				this.OnMaNhomNSChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HieuLuc_NS", DbType="Bit")]
	public System.Nullable<bool> HieuLuc_NS
	{
		get
		{
			return this._HieuLuc_NS;
		}
		set
		{
			if ((this._HieuLuc_NS != value))
			{
				this.OnHieuLuc_NSChanging(value);
				this.SendPropertyChanging();
				this._HieuLuc_NS = value;
				this.SendPropertyChanged("HieuLuc_NS");
				this.OnHieuLuc_NSChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DmChiPhi")]
public partial class DmChiPhi : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MSChiPhi;
	
	private string _MaNganSach;
	
	private string _DienGiai;
	
	private string _DienGiai_NS;
	
	private System.Nullable<bool> _HIEULUC;
	
	private string _MANV;
	
	private System.Nullable<System.DateTime> _NgayTao;
	
	private string _MANVCN;
	
	private System.Nullable<System.DateTime> _NgayCN;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSChiPhiChanging(string value);
    partial void OnMSChiPhiChanged();
    partial void OnMaNganSachChanging(string value);
    partial void OnMaNganSachChanged();
    partial void OnDienGiaiChanging(string value);
    partial void OnDienGiaiChanged();
    partial void OnDienGiai_NSChanging(string value);
    partial void OnDienGiai_NSChanged();
    partial void OnHIEULUCChanging(System.Nullable<bool> value);
    partial void OnHIEULUCChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnMANVCNChanging(string value);
    partial void OnMANVCNChanged();
    partial void OnNgayCNChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCNChanged();
    #endregion
	
	public DmChiPhi()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSChiPhi", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MSChiPhi
	{
		get
		{
			return this._MSChiPhi;
		}
		set
		{
			if ((this._MSChiPhi != value))
			{
				this.OnMSChiPhiChanging(value);
				this.SendPropertyChanging();
				this._MSChiPhi = value;
				this.SendPropertyChanged("MSChiPhi");
				this.OnMSChiPhiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNganSach", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaNganSach
	{
		get
		{
			return this._MaNganSach;
		}
		set
		{
			if ((this._MaNganSach != value))
			{
				this.OnMaNganSachChanging(value);
				this.SendPropertyChanging();
				this._MaNganSach = value;
				this.SendPropertyChanged("MaNganSach");
				this.OnMaNganSachChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienGiai", DbType="NVarChar(200)")]
	public string DienGiai
	{
		get
		{
			return this._DienGiai;
		}
		set
		{
			if ((this._DienGiai != value))
			{
				this.OnDienGiaiChanging(value);
				this.SendPropertyChanging();
				this._DienGiai = value;
				this.SendPropertyChanged("DienGiai");
				this.OnDienGiaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienGiai_NS", DbType="NVarChar(200)")]
	public string DienGiai_NS
	{
		get
		{
			return this._DienGiai_NS;
		}
		set
		{
			if ((this._DienGiai_NS != value))
			{
				this.OnDienGiai_NSChanging(value);
				this.SendPropertyChanging();
				this._DienGiai_NS = value;
				this.SendPropertyChanged("DienGiai_NS");
				this.OnDienGiai_NSChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEULUC", DbType="Bit")]
	public System.Nullable<bool> HIEULUC
	{
		get
		{
			return this._HIEULUC;
		}
		set
		{
			if ((this._HIEULUC != value))
			{
				this.OnHIEULUCChanging(value);
				this.SendPropertyChanging();
				this._HIEULUC = value;
				this.SendPropertyChanged("HIEULUC");
				this.OnHIEULUCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(50)")]
	public string MANV
	{
		get
		{
			return this._MANV;
		}
		set
		{
			if ((this._MANV != value))
			{
				this.OnMANVChanging(value);
				this.SendPropertyChanging();
				this._MANV = value;
				this.SendPropertyChanged("MANV");
				this.OnMANVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgayTao
	{
		get
		{
			return this._NgayTao;
		}
		set
		{
			if ((this._NgayTao != value))
			{
				this.OnNgayTaoChanging(value);
				this.SendPropertyChanging();
				this._NgayTao = value;
				this.SendPropertyChanged("NgayTao");
				this.OnNgayTaoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANVCN", DbType="VarChar(50)")]
	public string MANVCN
	{
		get
		{
			return this._MANVCN;
		}
		set
		{
			if ((this._MANVCN != value))
			{
				this.OnMANVCNChanging(value);
				this.SendPropertyChanging();
				this._MANVCN = value;
				this.SendPropertyChanged("MANVCN");
				this.OnMANVCNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCN", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgayCN
	{
		get
		{
			return this._NgayCN;
		}
		set
		{
			if ((this._NgayCN != value))
			{
				this.OnNgayCNChanging(value);
				this.SendPropertyChanging();
				this._NgayCN = value;
				this.SendPropertyChanged("NgayCN");
				this.OnNgayCNChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DmNhomNganSach")]
public partial class DmNhomNganSach : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaNhomNS;
	
	private string _DienGiai;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomNSChanging(string value);
    partial void OnMaNhomNSChanged();
    partial void OnDienGiaiChanging(string value);
    partial void OnDienGiaiChanged();
    #endregion
	
	public DmNhomNganSach()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomNS", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaNhomNS
	{
		get
		{
			return this._MaNhomNS;
		}
		set
		{
			if ((this._MaNhomNS != value))
			{
				this.OnMaNhomNSChanging(value);
				this.SendPropertyChanging();
				this._MaNhomNS = value;
				this.SendPropertyChanged("MaNhomNS");
				this.OnMaNhomNSChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienGiai", DbType="NVarChar(100)")]
	public string DienGiai
	{
		get
		{
			return this._DienGiai;
		}
		set
		{
			if ((this._DienGiai != value))
			{
				this.OnDienGiaiChanging(value);
				this.SendPropertyChanging();
				this._DienGiai = value;
				this.SendPropertyChanged("DienGiai");
				this.OnDienGiaiChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoanNganHang")]
public partial class TaiKhoanNganHang : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MADV;
	
	private string _MANV;
	
	private string _TenNganHang;
	
	private string _SoTaiKhoan;
	
	private string _TenTaiKhoan;
	
	private string _Ghichu;
	
	private System.Nullable<bool> _HieuLuc;
	
	private int _ID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADVChanging(string value);
    partial void OnMADVChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnTenNganHangChanging(string value);
    partial void OnTenNganHangChanged();
    partial void OnSoTaiKhoanChanging(string value);
    partial void OnSoTaiKhoanChanged();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    partial void OnHieuLucChanging(System.Nullable<bool> value);
    partial void OnHieuLucChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
	
	public TaiKhoanNganHang()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string MADV
	{
		get
		{
			return this._MADV;
		}
		set
		{
			if ((this._MADV != value))
			{
				this.OnMADVChanging(value);
				this.SendPropertyChanging();
				this._MADV = value;
				this.SendPropertyChanged("MADV");
				this.OnMADVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string MANV
	{
		get
		{
			return this._MANV;
		}
		set
		{
			if ((this._MANV != value))
			{
				this.OnMANVChanging(value);
				this.SendPropertyChanging();
				this._MANV = value;
				this.SendPropertyChanged("MANV");
				this.OnMANVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNganHang", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string TenNganHang
	{
		get
		{
			return this._TenNganHang;
		}
		set
		{
			if ((this._TenNganHang != value))
			{
				this.OnTenNganHangChanging(value);
				this.SendPropertyChanging();
				this._TenNganHang = value;
				this.SendPropertyChanged("TenNganHang");
				this.OnTenNganHangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTaiKhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string SoTaiKhoan
	{
		get
		{
			return this._SoTaiKhoan;
		}
		set
		{
			if ((this._SoTaiKhoan != value))
			{
				this.OnSoTaiKhoanChanging(value);
				this.SendPropertyChanging();
				this._SoTaiKhoan = value;
				this.SendPropertyChanged("SoTaiKhoan");
				this.OnSoTaiKhoanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string TenTaiKhoan
	{
		get
		{
			return this._TenTaiKhoan;
		}
		set
		{
			if ((this._TenTaiKhoan != value))
			{
				this.OnTenTaiKhoanChanging(value);
				this.SendPropertyChanging();
				this._TenTaiKhoan = value;
				this.SendPropertyChanged("TenTaiKhoan");
				this.OnTenTaiKhoanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NVarChar(MAX)")]
	public string Ghichu
	{
		get
		{
			return this._Ghichu;
		}
		set
		{
			if ((this._Ghichu != value))
			{
				this.OnGhichuChanging(value);
				this.SendPropertyChanging();
				this._Ghichu = value;
				this.SendPropertyChanged("Ghichu");
				this.OnGhichuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HieuLuc", DbType="Bit")]
	public System.Nullable<bool> HieuLuc
	{
		get
		{
			return this._HieuLuc;
		}
		set
		{
			if ((this._HieuLuc != value))
			{
				this.OnHieuLucChanging(value);
				this.SendPropertyChanging();
				this._HieuLuc = value;
				this.SendPropertyChanged("HieuLuc");
				this.OnHieuLucChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ImportTaiKhoanNganHang_tmp")]
public partial class ImportTaiKhoanNganHang_tmp : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MADV;
	
	private string _MANV;
	
	private string _TENNGANHANG;
	
	private string _SOTAIKHOAN;
	
	private string _TENTAIKHOAN;
	
	private string _GHICHU;
	
	private string _TENMAYTINH;
	
	private System.Nullable<bool> _Chon;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADVChanging(string value);
    partial void OnMADVChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnTENNGANHANGChanging(string value);
    partial void OnTENNGANHANGChanged();
    partial void OnSOTAIKHOANChanging(string value);
    partial void OnSOTAIKHOANChanged();
    partial void OnTENTAIKHOANChanging(string value);
    partial void OnTENTAIKHOANChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    partial void OnTENMAYTINHChanging(string value);
    partial void OnTENMAYTINHChanged();
    partial void OnChonChanging(System.Nullable<bool> value);
    partial void OnChonChanged();
    #endregion
	
	public ImportTaiKhoanNganHang_tmp()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADV", DbType="NVarChar(1000)")]
	public string MADV
	{
		get
		{
			return this._MADV;
		}
		set
		{
			if ((this._MADV != value))
			{
				this.OnMADVChanging(value);
				this.SendPropertyChanging();
				this._MADV = value;
				this.SendPropertyChanged("MADV");
				this.OnMADVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MANV
	{
		get
		{
			return this._MANV;
		}
		set
		{
			if ((this._MANV != value))
			{
				this.OnMANVChanging(value);
				this.SendPropertyChanging();
				this._MANV = value;
				this.SendPropertyChanged("MANV");
				this.OnMANVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNGANHANG", DbType="NVarChar(1000)")]
	public string TENNGANHANG
	{
		get
		{
			return this._TENNGANHANG;
		}
		set
		{
			if ((this._TENNGANHANG != value))
			{
				this.OnTENNGANHANGChanging(value);
				this.SendPropertyChanging();
				this._TENNGANHANG = value;
				this.SendPropertyChanged("TENNGANHANG");
				this.OnTENNGANHANGChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOTAIKHOAN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SOTAIKHOAN
	{
		get
		{
			return this._SOTAIKHOAN;
		}
		set
		{
			if ((this._SOTAIKHOAN != value))
			{
				this.OnSOTAIKHOANChanging(value);
				this.SendPropertyChanging();
				this._SOTAIKHOAN = value;
				this.SendPropertyChanged("SOTAIKHOAN");
				this.OnSOTAIKHOANChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTAIKHOAN", DbType="NVarChar(1000)")]
	public string TENTAIKHOAN
	{
		get
		{
			return this._TENTAIKHOAN;
		}
		set
		{
			if ((this._TENTAIKHOAN != value))
			{
				this.OnTENTAIKHOANChanging(value);
				this.SendPropertyChanging();
				this._TENTAIKHOAN = value;
				this.SendPropertyChanged("TENTAIKHOAN");
				this.OnTENTAIKHOANChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(1000)")]
	public string GHICHU
	{
		get
		{
			return this._GHICHU;
		}
		set
		{
			if ((this._GHICHU != value))
			{
				this.OnGHICHUChanging(value);
				this.SendPropertyChanging();
				this._GHICHU = value;
				this.SendPropertyChanged("GHICHU");
				this.OnGHICHUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENMAYTINH", DbType="VarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TENMAYTINH
	{
		get
		{
			return this._TENMAYTINH;
		}
		set
		{
			if ((this._TENMAYTINH != value))
			{
				this.OnTENMAYTINHChanging(value);
				this.SendPropertyChanging();
				this._TENMAYTINH = value;
				this.SendPropertyChanged("TENMAYTINH");
				this.OnTENMAYTINHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chon", DbType="Bit")]
	public System.Nullable<bool> Chon
	{
		get
		{
			return this._Chon;
		}
		set
		{
			if ((this._Chon != value))
			{
				this.OnChonChanging(value);
				this.SendPropertyChanging();
				this._Chon = value;
				this.SendPropertyChanged("Chon");
				this.OnChonChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class sp_ChuyenNganSachThuaCuaThangTruocResult
{
	
	private int _KetQua;
	
	private System.DateTime _NgayCapNhat;
	
	private System.Nullable<System.Guid> _Id;
	
	public sp_ChuyenNganSachThuaCuaThangTruocResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetQua", DbType="Int NOT NULL")]
	public int KetQua
	{
		get
		{
			return this._KetQua;
		}
		set
		{
			if ((this._KetQua != value))
			{
				this._KetQua = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime NOT NULL")]
	public System.DateTime NgayCapNhat
	{
		get
		{
			return this._NgayCapNhat;
		}
		set
		{
			if ((this._NgayCapNhat != value))
			{
				this._NgayCapNhat = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
}

public partial class Sp_KiemTraNganSachDuResult
{
	
	private string _Thang;
	
	private string _Nam;
	
	private string _MaDV;
	
	private string _MSChiphi;
	
	private System.Nullable<decimal> _Sotien;
	
	private string _ID_Khoa;
	
	private string _ID_khoaCT;
	
	public Sp_KiemTraNganSachDuResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="VarChar(2)")]
	public string Thang
	{
		get
		{
			return this._Thang;
		}
		set
		{
			if ((this._Thang != value))
			{
				this._Thang = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="VarChar(4)")]
	public string Nam
	{
		get
		{
			return this._Nam;
		}
		set
		{
			if ((this._Nam != value))
			{
				this._Nam = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="VarChar(50)")]
	public string MaDV
	{
		get
		{
			return this._MaDV;
		}
		set
		{
			if ((this._MaDV != value))
			{
				this._MaDV = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSChiphi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string MSChiphi
	{
		get
		{
			return this._MSChiphi;
		}
		set
		{
			if ((this._MSChiphi != value))
			{
				this._MSChiphi = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sotien", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Sotien
	{
		get
		{
			return this._Sotien;
		}
		set
		{
			if ((this._Sotien != value))
			{
				this._Sotien = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Khoa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string ID_Khoa
	{
		get
		{
			return this._ID_Khoa;
		}
		set
		{
			if ((this._ID_Khoa != value))
			{
				this._ID_Khoa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_khoaCT", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string ID_khoaCT
	{
		get
		{
			return this._ID_khoaCT;
		}
		set
		{
			if ((this._ID_khoaCT != value))
			{
				this._ID_khoaCT = value;
			}
		}
	}
}

public partial class Sp_UpdateNganSachSauKhiChuyenThuaResult
{
	
	private int _KetQua;
	
	private System.DateTime _NgayCapNhat;
	
	private System.Nullable<System.Guid> _Id;
	
	public Sp_UpdateNganSachSauKhiChuyenThuaResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetQua", DbType="Int NOT NULL")]
	public int KetQua
	{
		get
		{
			return this._KetQua;
		}
		set
		{
			if ((this._KetQua != value))
			{
				this._KetQua = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime NOT NULL")]
	public System.DateTime NgayCapNhat
	{
		get
		{
			return this._NgayCapNhat;
		}
		set
		{
			if ((this._NgayCapNhat != value))
			{
				this._NgayCapNhat = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
}
#pragma warning restore 1591
