#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="wqlvattu")]
public partial class QLVattuDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertDMNHANVIEN(DMNHANVIEN instance);
  partial void UpdateDMNHANVIEN(DMNHANVIEN instance);
  partial void DeleteDMNHANVIEN(DMNHANVIEN instance);
  partial void InsertDMDONVI(DMDONVI instance);
  partial void UpdateDMDONVI(DMDONVI instance);
  partial void DeleteDMDONVI(DMDONVI instance);
  #endregion
	
	public QLVattuDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectDB_wqlvattu"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public QLVattuDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QLVattuDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QLVattuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QLVattuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<DMNHANVIEN> DMNHANVIENs
	{
		get
		{
			return this.GetTable<DMNHANVIEN>();
		}
	}
	
	public System.Data.Linq.Table<DMDONVI> DMDONVIs
	{
		get
		{
			return this.GetTable<DMDONVI>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DMNHANVIEN")]
public partial class DMNHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MANV;
	
	private string _HOTEN;
	
	private string _ChucVu;
	
	private string _MADV;
	
	private string _EMail;
	
	private System.Nullable<byte> _LapPhieu;
	
	private System.Nullable<byte> _TPB_kiemtra;
	
	private System.Nullable<byte> _XemXet;
	
	private System.Nullable<byte> _PheDuyet;
	
	private System.Nullable<byte> _TiepNhan;
	
	private string _Passwordid;
	
	private System.Nullable<byte> _HieuLuc;
	
	private System.Nullable<byte> _KIEMTRA;
	
	private string _MABP;
	
	private string _IDMaDV;
	
	private System.Nullable<bool> _QuanTri;
	
	private string _CMND;
	
	private System.Nullable<System.DateTime> _NgayCap;
	
	private string _NoiCap;
	
	private System.Nullable<int> _quyencpn;
	
	private System.Data.Linq.Binary _Chuki;
	
	private System.Nullable<bool> _TinhGTMay;
	
	private System.Nullable<System.DateTime> _NgayHieuLucPass;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnMADVChanging(string value);
    partial void OnMADVChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnLapPhieuChanging(System.Nullable<byte> value);
    partial void OnLapPhieuChanged();
    partial void OnTPB_kiemtraChanging(System.Nullable<byte> value);
    partial void OnTPB_kiemtraChanged();
    partial void OnXemXetChanging(System.Nullable<byte> value);
    partial void OnXemXetChanged();
    partial void OnPheDuyetChanging(System.Nullable<byte> value);
    partial void OnPheDuyetChanged();
    partial void OnTiepNhanChanging(System.Nullable<byte> value);
    partial void OnTiepNhanChanged();
    partial void OnPasswordidChanging(string value);
    partial void OnPasswordidChanged();
    partial void OnHieuLucChanging(System.Nullable<byte> value);
    partial void OnHieuLucChanged();
    partial void OnKIEMTRAChanging(System.Nullable<byte> value);
    partial void OnKIEMTRAChanged();
    partial void OnMABPChanging(string value);
    partial void OnMABPChanged();
    partial void OnIDMaDVChanging(string value);
    partial void OnIDMaDVChanged();
    partial void OnQuanTriChanging(System.Nullable<bool> value);
    partial void OnQuanTriChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnNgayCapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapChanged();
    partial void OnNoiCapChanging(string value);
    partial void OnNoiCapChanged();
    partial void OnquyencpnChanging(System.Nullable<int> value);
    partial void OnquyencpnChanged();
    partial void OnChukiChanging(System.Data.Linq.Binary value);
    partial void OnChukiChanged();
    partial void OnTinhGTMayChanging(System.Nullable<bool> value);
    partial void OnTinhGTMayChanged();
    partial void OnNgayHieuLucPassChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHieuLucPassChanged();
    #endregion
	
	public DMNHANVIEN()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MANV
	{
		get
		{
			return this._MANV;
		}
		set
		{
			if ((this._MANV != value))
			{
				this.OnMANVChanging(value);
				this.SendPropertyChanging();
				this._MANV = value;
				this.SendPropertyChanged("MANV");
				this.OnMANVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(100)")]
	public string HOTEN
	{
		get
		{
			return this._HOTEN;
		}
		set
		{
			if ((this._HOTEN != value))
			{
				this.OnHOTENChanging(value);
				this.SendPropertyChanging();
				this._HOTEN = value;
				this.SendPropertyChanged("HOTEN");
				this.OnHOTENChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
	public string ChucVu
	{
		get
		{
			return this._ChucVu;
		}
		set
		{
			if ((this._ChucVu != value))
			{
				this.OnChucVuChanging(value);
				this.SendPropertyChanging();
				this._ChucVu = value;
				this.SendPropertyChanged("ChucVu");
				this.OnChucVuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADV", DbType="VarChar(50)")]
	public string MADV
	{
		get
		{
			return this._MADV;
		}
		set
		{
			if ((this._MADV != value))
			{
				this.OnMADVChanging(value);
				this.SendPropertyChanging();
				this._MADV = value;
				this.SendPropertyChanged("MADV");
				this.OnMADVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(50)")]
	public string EMail
	{
		get
		{
			return this._EMail;
		}
		set
		{
			if ((this._EMail != value))
			{
				this.OnEMailChanging(value);
				this.SendPropertyChanging();
				this._EMail = value;
				this.SendPropertyChanged("EMail");
				this.OnEMailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LapPhieu", DbType="TinyInt")]
	public System.Nullable<byte> LapPhieu
	{
		get
		{
			return this._LapPhieu;
		}
		set
		{
			if ((this._LapPhieu != value))
			{
				this.OnLapPhieuChanging(value);
				this.SendPropertyChanging();
				this._LapPhieu = value;
				this.SendPropertyChanged("LapPhieu");
				this.OnLapPhieuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TPB_kiemtra", DbType="TinyInt")]
	public System.Nullable<byte> TPB_kiemtra
	{
		get
		{
			return this._TPB_kiemtra;
		}
		set
		{
			if ((this._TPB_kiemtra != value))
			{
				this.OnTPB_kiemtraChanging(value);
				this.SendPropertyChanging();
				this._TPB_kiemtra = value;
				this.SendPropertyChanged("TPB_kiemtra");
				this.OnTPB_kiemtraChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XemXet", DbType="TinyInt")]
	public System.Nullable<byte> XemXet
	{
		get
		{
			return this._XemXet;
		}
		set
		{
			if ((this._XemXet != value))
			{
				this.OnXemXetChanging(value);
				this.SendPropertyChanging();
				this._XemXet = value;
				this.SendPropertyChanged("XemXet");
				this.OnXemXetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PheDuyet", DbType="TinyInt")]
	public System.Nullable<byte> PheDuyet
	{
		get
		{
			return this._PheDuyet;
		}
		set
		{
			if ((this._PheDuyet != value))
			{
				this.OnPheDuyetChanging(value);
				this.SendPropertyChanging();
				this._PheDuyet = value;
				this.SendPropertyChanged("PheDuyet");
				this.OnPheDuyetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TiepNhan", DbType="TinyInt")]
	public System.Nullable<byte> TiepNhan
	{
		get
		{
			return this._TiepNhan;
		}
		set
		{
			if ((this._TiepNhan != value))
			{
				this.OnTiepNhanChanging(value);
				this.SendPropertyChanging();
				this._TiepNhan = value;
				this.SendPropertyChanged("TiepNhan");
				this.OnTiepNhanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passwordid", DbType="VarChar(50)")]
	public string Passwordid
	{
		get
		{
			return this._Passwordid;
		}
		set
		{
			if ((this._Passwordid != value))
			{
				this.OnPasswordidChanging(value);
				this.SendPropertyChanging();
				this._Passwordid = value;
				this.SendPropertyChanged("Passwordid");
				this.OnPasswordidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HieuLuc", DbType="TinyInt")]
	public System.Nullable<byte> HieuLuc
	{
		get
		{
			return this._HieuLuc;
		}
		set
		{
			if ((this._HieuLuc != value))
			{
				this.OnHieuLucChanging(value);
				this.SendPropertyChanging();
				this._HieuLuc = value;
				this.SendPropertyChanged("HieuLuc");
				this.OnHieuLucChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIEMTRA", DbType="TinyInt")]
	public System.Nullable<byte> KIEMTRA
	{
		get
		{
			return this._KIEMTRA;
		}
		set
		{
			if ((this._KIEMTRA != value))
			{
				this.OnKIEMTRAChanging(value);
				this.SendPropertyChanging();
				this._KIEMTRA = value;
				this.SendPropertyChanged("KIEMTRA");
				this.OnKIEMTRAChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABP", DbType="VarChar(50)")]
	public string MABP
	{
		get
		{
			return this._MABP;
		}
		set
		{
			if ((this._MABP != value))
			{
				this.OnMABPChanging(value);
				this.SendPropertyChanging();
				this._MABP = value;
				this.SendPropertyChanged("MABP");
				this.OnMABPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMaDV", DbType="VarChar(20)")]
	public string IDMaDV
	{
		get
		{
			return this._IDMaDV;
		}
		set
		{
			if ((this._IDMaDV != value))
			{
				this.OnIDMaDVChanging(value);
				this.SendPropertyChanging();
				this._IDMaDV = value;
				this.SendPropertyChanged("IDMaDV");
				this.OnIDMaDVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuanTri", DbType="Bit")]
	public System.Nullable<bool> QuanTri
	{
		get
		{
			return this._QuanTri;
		}
		set
		{
			if ((this._QuanTri != value))
			{
				this.OnQuanTriChanging(value);
				this.SendPropertyChanging();
				this._QuanTri = value;
				this.SendPropertyChanged("QuanTri");
				this.OnQuanTriChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(20)")]
	public string CMND
	{
		get
		{
			return this._CMND;
		}
		set
		{
			if ((this._CMND != value))
			{
				this.OnCMNDChanging(value);
				this.SendPropertyChanging();
				this._CMND = value;
				this.SendPropertyChanged("CMND");
				this.OnCMNDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgayCap
	{
		get
		{
			return this._NgayCap;
		}
		set
		{
			if ((this._NgayCap != value))
			{
				this.OnNgayCapChanging(value);
				this.SendPropertyChanging();
				this._NgayCap = value;
				this.SendPropertyChanged("NgayCap");
				this.OnNgayCapChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCap", DbType="NVarChar(50)")]
	public string NoiCap
	{
		get
		{
			return this._NoiCap;
		}
		set
		{
			if ((this._NoiCap != value))
			{
				this.OnNoiCapChanging(value);
				this.SendPropertyChanging();
				this._NoiCap = value;
				this.SendPropertyChanged("NoiCap");
				this.OnNoiCapChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyencpn", DbType="Int")]
	public System.Nullable<int> quyencpn
	{
		get
		{
			return this._quyencpn;
		}
		set
		{
			if ((this._quyencpn != value))
			{
				this.OnquyencpnChanging(value);
				this.SendPropertyChanging();
				this._quyencpn = value;
				this.SendPropertyChanged("quyencpn");
				this.OnquyencpnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chuki", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary Chuki
	{
		get
		{
			return this._Chuki;
		}
		set
		{
			if ((this._Chuki != value))
			{
				this.OnChukiChanging(value);
				this.SendPropertyChanging();
				this._Chuki = value;
				this.SendPropertyChanged("Chuki");
				this.OnChukiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhGTMay", DbType="Bit")]
	public System.Nullable<bool> TinhGTMay
	{
		get
		{
			return this._TinhGTMay;
		}
		set
		{
			if ((this._TinhGTMay != value))
			{
				this.OnTinhGTMayChanging(value);
				this.SendPropertyChanging();
				this._TinhGTMay = value;
				this.SendPropertyChanged("TinhGTMay");
				this.OnTinhGTMayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHieuLucPass", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgayHieuLucPass
	{
		get
		{
			return this._NgayHieuLucPass;
		}
		set
		{
			if ((this._NgayHieuLucPass != value))
			{
				this.OnNgayHieuLucPassChanging(value);
				this.SendPropertyChanging();
				this._NgayHieuLucPass = value;
				this.SendPropertyChanged("NgayHieuLucPass");
				this.OnNgayHieuLucPassChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DMDONVI")]
public partial class DMDONVI : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _IDMaDV;
	
	private string _MaDonVi;
	
	private string _TenDonVi;
	
	private string _KiHieu;
	
	private System.Nullable<byte> _HieuLuc;
	
	private string _TenGiaoDich_DV;
	
	private string _DiaChi_DV;
	
	private string _SoDienThoai_DV;
	
	private string _Fax_DV;
	
	private System.Nullable<bool> _Thanhpham_Xuat;
	
	private System.Nullable<bool> _Thanhpham_Nhap;
	
	private System.Nullable<bool> _Moc_Nhap;
	
	private System.Nullable<bool> _Moc_Xuat;
	
	private System.Nullable<bool> _BPDatbong;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDMaDVChanging(string value);
    partial void OnIDMaDVChanged();
    partial void OnMaDonViChanging(string value);
    partial void OnMaDonViChanged();
    partial void OnTenDonViChanging(string value);
    partial void OnTenDonViChanged();
    partial void OnKiHieuChanging(string value);
    partial void OnKiHieuChanged();
    partial void OnHieuLucChanging(System.Nullable<byte> value);
    partial void OnHieuLucChanged();
    partial void OnTenGiaoDich_DVChanging(string value);
    partial void OnTenGiaoDich_DVChanged();
    partial void OnDiaChi_DVChanging(string value);
    partial void OnDiaChi_DVChanged();
    partial void OnSoDienThoai_DVChanging(string value);
    partial void OnSoDienThoai_DVChanged();
    partial void OnFax_DVChanging(string value);
    partial void OnFax_DVChanged();
    partial void OnThanhpham_XuatChanging(System.Nullable<bool> value);
    partial void OnThanhpham_XuatChanged();
    partial void OnThanhpham_NhapChanging(System.Nullable<bool> value);
    partial void OnThanhpham_NhapChanged();
    partial void OnMoc_NhapChanging(System.Nullable<bool> value);
    partial void OnMoc_NhapChanged();
    partial void OnMoc_XuatChanging(System.Nullable<bool> value);
    partial void OnMoc_XuatChanged();
    partial void OnBPDatbongChanging(System.Nullable<bool> value);
    partial void OnBPDatbongChanged();
    #endregion
	
	public DMDONVI()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMaDV", DbType="VarChar(20)")]
	public string IDMaDV
	{
		get
		{
			return this._IDMaDV;
		}
		set
		{
			if ((this._IDMaDV != value))
			{
				this.OnIDMaDVChanging(value);
				this.SendPropertyChanging();
				this._IDMaDV = value;
				this.SendPropertyChanged("IDMaDV");
				this.OnIDMaDVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonVi", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaDonVi
	{
		get
		{
			return this._MaDonVi;
		}
		set
		{
			if ((this._MaDonVi != value))
			{
				this.OnMaDonViChanging(value);
				this.SendPropertyChanging();
				this._MaDonVi = value;
				this.SendPropertyChanged("MaDonVi");
				this.OnMaDonViChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonVi", DbType="NVarChar(200)")]
	public string TenDonVi
	{
		get
		{
			return this._TenDonVi;
		}
		set
		{
			if ((this._TenDonVi != value))
			{
				this.OnTenDonViChanging(value);
				this.SendPropertyChanging();
				this._TenDonVi = value;
				this.SendPropertyChanged("TenDonVi");
				this.OnTenDonViChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KiHieu", DbType="VarChar(50)")]
	public string KiHieu
	{
		get
		{
			return this._KiHieu;
		}
		set
		{
			if ((this._KiHieu != value))
			{
				this.OnKiHieuChanging(value);
				this.SendPropertyChanging();
				this._KiHieu = value;
				this.SendPropertyChanged("KiHieu");
				this.OnKiHieuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HieuLuc", DbType="TinyInt")]
	public System.Nullable<byte> HieuLuc
	{
		get
		{
			return this._HieuLuc;
		}
		set
		{
			if ((this._HieuLuc != value))
			{
				this.OnHieuLucChanging(value);
				this.SendPropertyChanging();
				this._HieuLuc = value;
				this.SendPropertyChanged("HieuLuc");
				this.OnHieuLucChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiaoDich_DV", DbType="NVarChar(MAX)")]
	public string TenGiaoDich_DV
	{
		get
		{
			return this._TenGiaoDich_DV;
		}
		set
		{
			if ((this._TenGiaoDich_DV != value))
			{
				this.OnTenGiaoDich_DVChanging(value);
				this.SendPropertyChanging();
				this._TenGiaoDich_DV = value;
				this.SendPropertyChanged("TenGiaoDich_DV");
				this.OnTenGiaoDich_DVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi_DV", DbType="NVarChar(MAX)")]
	public string DiaChi_DV
	{
		get
		{
			return this._DiaChi_DV;
		}
		set
		{
			if ((this._DiaChi_DV != value))
			{
				this.OnDiaChi_DVChanging(value);
				this.SendPropertyChanging();
				this._DiaChi_DV = value;
				this.SendPropertyChanged("DiaChi_DV");
				this.OnDiaChi_DVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai_DV", DbType="NVarChar(MAX)")]
	public string SoDienThoai_DV
	{
		get
		{
			return this._SoDienThoai_DV;
		}
		set
		{
			if ((this._SoDienThoai_DV != value))
			{
				this.OnSoDienThoai_DVChanging(value);
				this.SendPropertyChanging();
				this._SoDienThoai_DV = value;
				this.SendPropertyChanged("SoDienThoai_DV");
				this.OnSoDienThoai_DVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax_DV", DbType="NVarChar(MAX)")]
	public string Fax_DV
	{
		get
		{
			return this._Fax_DV;
		}
		set
		{
			if ((this._Fax_DV != value))
			{
				this.OnFax_DVChanging(value);
				this.SendPropertyChanging();
				this._Fax_DV = value;
				this.SendPropertyChanged("Fax_DV");
				this.OnFax_DVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thanhpham_Xuat", DbType="Bit")]
	public System.Nullable<bool> Thanhpham_Xuat
	{
		get
		{
			return this._Thanhpham_Xuat;
		}
		set
		{
			if ((this._Thanhpham_Xuat != value))
			{
				this.OnThanhpham_XuatChanging(value);
				this.SendPropertyChanging();
				this._Thanhpham_Xuat = value;
				this.SendPropertyChanged("Thanhpham_Xuat");
				this.OnThanhpham_XuatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thanhpham_Nhap", DbType="Bit")]
	public System.Nullable<bool> Thanhpham_Nhap
	{
		get
		{
			return this._Thanhpham_Nhap;
		}
		set
		{
			if ((this._Thanhpham_Nhap != value))
			{
				this.OnThanhpham_NhapChanging(value);
				this.SendPropertyChanging();
				this._Thanhpham_Nhap = value;
				this.SendPropertyChanged("Thanhpham_Nhap");
				this.OnThanhpham_NhapChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moc_Nhap", DbType="Bit")]
	public System.Nullable<bool> Moc_Nhap
	{
		get
		{
			return this._Moc_Nhap;
		}
		set
		{
			if ((this._Moc_Nhap != value))
			{
				this.OnMoc_NhapChanging(value);
				this.SendPropertyChanging();
				this._Moc_Nhap = value;
				this.SendPropertyChanged("Moc_Nhap");
				this.OnMoc_NhapChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moc_Xuat", DbType="Bit")]
	public System.Nullable<bool> Moc_Xuat
	{
		get
		{
			return this._Moc_Xuat;
		}
		set
		{
			if ((this._Moc_Xuat != value))
			{
				this.OnMoc_XuatChanging(value);
				this.SendPropertyChanging();
				this._Moc_Xuat = value;
				this.SendPropertyChanged("Moc_Xuat");
				this.OnMoc_XuatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPDatbong", DbType="Bit")]
	public System.Nullable<bool> BPDatbong
	{
		get
		{
			return this._BPDatbong;
		}
		set
		{
			if ((this._BPDatbong != value))
			{
				this.OnBPDatbongChanging(value);
				this.SendPropertyChanging();
				this._BPDatbong = value;
				this.SendPropertyChanged("BPDatbong");
				this.OnBPDatbongChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
